local PBR = require "defold-pbr-extension/core"
local dirtylarry = require "dirtylarry/dirtylarry"

local function position_widgets(self)
	local height = 24
	local start_y = -96
	local start_x = 24
	local text_scale = 0.3
	local i = 0

	gui.set_position(self.environment_label, vmath.vector3(12, start_y - height * i, 0))
	gui.set_scale(self.environment_label, vmath.vector3(text_scale * 2, text_scale * 2, 1))

	i = i + 1
	for name, widget in pairs(self.env_selection_wid) do
		gui.set_position(widget.radio, vmath.vector3(start_x, start_y - height * i, 0))
		gui.set_position(widget.label, vmath.vector3(start_x + 24, start_y - height * i, 0))
		gui.set_scale(widget.radio, vmath.vector3(text_scale, text_scale, 1))
		gui.set_scale(widget.label, vmath.vector3(text_scale, text_scale, 1))
		gui.set_text(widget.label, name)
		i = i + 1
	end
end

function init(self)
	msg.post(".", "acquire_input_focus")

	local radio_radio = gui.get_node("template/larryradio")
	local radio_label = gui.get_node("template/larrylabel")
	local left_pane = gui.get_node("debug-left-pane")

	self.environment_label = gui.clone(radio_label)
	gui.set_text(self.environment_label, "Environment")
	gui.set_parent(self.environment_label, left_pane)

	self.env_selection_wid = {}
	for name, _ in pairs(PBR.get_environments()) do
		self.env_selection_wid[name] = {
			radio = gui.clone(radio_radio),
			label = gui.clone(radio_label),
		}

		gui.set_parent(self.env_selection_wid[name].radio, left_pane)
		gui.set_parent(self.env_selection_wid[name].label, left_pane)
		gui.set_id(self.env_selection_wid[name].radio, name .. "/larryradio")
		gui.set_id(self.env_selection_wid[name].label, name .. "/larrylabel")
	end

	self.is_locked = false
	self.show_settings = false
	position_widgets(self)
end

function on_input(self, action_id, action)
	dirtylarry:button("settings", action_id, action, function()
		self.show_settings = not self.show_settings
		if self.show_settings then
			gui.animate(gui.get_node("debug-left-pane"), "position.x", 0, gui.EASING_OUTEXPO, 0.5)
			gui.set_text(gui.get_node("settings/larrylabel"), "close")
		else
			gui.animate(gui.get_node("debug-left-pane"), "position.x", -500, gui.EASING_OUTEXPO, 0.5)
			gui.set_text(gui.get_node("settings/larrylabel"), "settings")
		end
	end)

	if self.show_settings then
		if dirtylarry:hit("debug-left-pane", action_id, action, function() end) then
			self.is_locked = true
		end

		local env = PBR.get_environment()
		local selected_env = env
		for name, _ in pairs(self.env_selection_wid) do
			selected_env = dirtylarry:radio(name, action_id, action, name, selected_env)
		end

		if env ~= selected_env then
			PBR.set_environment(selected_env)
		end

		if action.released then
			self.is_locked = false
		end

		return self.is_locked
	end
end
