function init(self)
    msg.post(".",        "acquire_input_focus")
    msg.post("@render:", "use_camera_projection")
    msg.post("camera",   "acquire_camera_focus")
    msg.post("#preview", "load")
end

function on_message(self, message_id, message, sender)
    if message_id == hash("proxy_loaded") then
        msg.post(sender, "init")
        msg.post(sender, "enable")
    elseif message_id == hash("set_light_intensity") then
        local light = message.index == 1 and "/key_light#light" or "/fill_light#light"
        go.set(light, "intensity", message.intensity)
    end
end
